# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20170802_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, default=7, max_digits=10, null=True),
        ),
    ]
