# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20170802_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='gatunek2',
            field=models.CharField(choices=[('Akcja', 'Akcja'), ('Dramat', 'Dramat'), ('Horror', 'Horror'), ('Komedia', 'Komedia'), ('Sci-fi', 'Sci-fi'), ('Thriller', 'Thriller'), ('Western', 'Western'), ('Wojenny', 'Wojenny')], default='-----', max_length=10),
        ),
        migrations.AddField(
            model_name='film',
            name='gatunek3',
            field=models.CharField(choices=[('Akcja', 'Akcja'), ('Dramat', 'Dramat'), ('Horror', 'Horror'), ('Komedia', 'Komedia'), ('Sci-fi', 'Sci-fi'), ('Thriller', 'Thriller'), ('Western', 'Western'), ('Wojenny', 'Wojenny')], default='-----', max_length=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, default=7.5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rok',
            field=models.IntegerField(default=2000, null=True),
        ),
    ]
