# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20170802_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='koko',
            field=models.CharField(default='', max_length=500),
        ),
    ]
