# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_auto_20170802_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='gatunek2',
            field=models.CharField(choices=[('Akcja', 'Akcja'), ('Dramat', 'Dramat'), ('Horror', 'Horror'), ('Komedia', 'Komedia'), ('Sci-fi', 'Sci-fi'), ('Thriller', 'Thriller'), ('Western', 'Western'), ('Wojenny', 'Wojenny')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='film',
            name='gatunek3',
            field=models.CharField(choices=[('Akcja', 'Akcja'), ('Dramat', 'Dramat'), ('Horror', 'Horror'), ('Komedia', 'Komedia'), ('Sci-fi', 'Sci-fi'), ('Thriller', 'Thriller'), ('Western', 'Western'), ('Wojenny', 'Wojenny')], default='1', max_length=10),
        ),
    ]
